/**
 * Build script for Antigravity Chrome Extension
 *
 * MV3 service workers do NOT support importScripts() for local extension files
 * (throws DOMException). The only reliable solution is to inline the TS engine
 * bundle directly into background.js at build time.
 *
 * Source files:
 *   background.src.js  — the service worker source (edit this)
 *   src/engine/        — TypeScript engine source (edit this)
 *
 * Output:
 *   background.js      — final service worker (engine inlined, loaded by Chrome)
 *   dist/AntigravityEngine.bundle.js — standalone engine bundle (for inspection)
 */

const esbuild = require('esbuild');
const fs = require('fs');

esbuild.build({
  entryPoints: ['src/engine/AntigravityEngine.ts'],
  bundle: true,
  outfile: 'dist/AntigravityEngine.bundle.js',
  format: 'iife',
  globalName: 'AntigravityCore',
  target: ['chrome100'],
  minify: false,
  sourcemap: false,
}).then(() => {

  const engineBundle = fs.readFileSync('dist/AntigravityEngine.bundle.js', 'utf8');
  const backgroundSrc = fs.readFileSync('background.src.js', 'utf8');

  // Strip the importScripts block from the source — replaced by inline bundle
  const IMPORT_SCRIPTS_BLOCK = /\/\/ Load compiled TS Engine\ntry \{[\s\S]*?\} catch \(e\) \{[\s\S]*?\}\n/;
  const strippedBackground = backgroundSrc.replace(
    IMPORT_SCRIPTS_BLOCK,
    '// TS Engine inlined below by build.js — do not add importScripts here\n'
  );

  const output =
    `// AUTO-GENERATED by build.js — edit background.src.js and src/engine/, then run: npm run build\n` +
    `// Engine bundle inlined to avoid MV3 importScripts DOMException.\n\n` +
    engineBundle + '\n\n' +
    strippedBackground;

  fs.writeFileSync('background.js', output);
  console.log('✅ background.js built (' + Math.round(output.length / 1024) + 'KB)');

}).catch((e) => {
  console.error('Build failed:', e);
  process.exit(1);
});
